<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['full_tag_open'] = '<div id="pagination-div-id" class="pagination pull-right"><ul>';
		$config['full_tag_close'] = '</ul></div>';
		$config['first_link'] = 'First';
		$config['last_link'] = 'Last';
		$config['first_tag_open']= '<li>'; 
		$config['first_tag_close']= '</li>'; 
		$config['last_tag_open']= '<li>';
		$config['last_tag_close']= '</li>';
		$config['next_tag_open'] = '<li>';
		$config['next_tag_close'] = '</li>';
		$config['prev_tag_open'] = '<li>';
		$config['prev_tag_close'] = '</li>';
		$config['next_link'] = 'Next';
		$config['prev_link'] = 'Prev';
		$config['cur_tag_open'] = '<li><a href="javascript:void(0)"><strong>';
		$config['cur_tag_close'] = '</strong></a></li>';
		$config['num_tag_open'] = '<li>';
		$config['num_tag_close'] = '</li>';		
		$config['uri_segment'] = 5;